enum AnimalKind {
  "Nicht in der Liste" = 0,
  "Alpenschneehase (Lepus timidus varronis)",
  "Auerhuhn (Tetrao urogallus)",
  "Baummarder/Edelmarder (Martes martes)",
  "Biber (Castor fiber)",
  "Bisamratte (Ondatra zibethicus)",
  "Buntspecht (Dendrocopos)",
  "Dachs (Meles meles)",
  "Damhirsch (Dama dama)",
  "Eichelhäher (Garrulus glandarius)",
  "Eichhörnchen (Sciurus vulgaris)",
  "Eisvogel (Alcedo atthis)",
  "Eule (Strigiformes)",
  "Feldhamster (Cricetus cricetus)",
  "Feldhase/Waldhase (Lepus europaeus)",
  "Feldmaus (Microtus arvalis)",
  "Feuersalamander (Salamandra salamandra) ",
  "Fischotter (Lutra lutra)",
  "Fledermaus (Microchiroptera)",
  "Fuchs (Vulpes vulpes)",
  "Gams (Rupicapra rupicapra)",
  "Goldschakal (Canis aureus)",
  "Grasfrosch (Rana temporaria)",
  "Graureiher (Ardea cinerea)",
  "Haselmaus (Muscardinus avellanarius)",
  "Igel (Erinaceus europaeus)",
  "Kanadagans (Branta canadensis)",
  "Kegelrobbe (Halichoerus grypus)",
  "Kolkrabe (Corvus corax)",
  "Kreuzspinne (Araneus)",
  "Kröte (Bufonidae)",
  "Königsfasan (Syrmaticus reevesii)",
  "Laubfrosch (Hyla arborea)",
  "Luchs (Lynx lynx)",
  "Marderhund (Nyctereutes procyonoides)",
  "Maulwurf (Talpa europaea)",
  "Molche (Pleurodelinae)",
  "Möwe (Larinae)",
  "Nerz (Mustela lutreola)",
  "Rebhuhn (Perdix perdix)",
  "Reh (Circus pygargus)",
  "Ringelnatter (Natrix natrix)",
  "Ringeltaube (Columba palumbus)",
  "Rothirsch (Cervus elaphus)",
  "Rotmilan (Milvus milvus)",
  "Schmetterling (Lepidoptera)",
  "Schreiadler (Clanga pomarina)",
  "Schwan (Cygnus)",
  "Schwarzspecht (Dryocopus martius)",
  "Schweinswahl (Phocoenidae)",
  "Seefrosch (Pelophylax ridibundus)",
  "Siebenschläfer (Glis glis)",
  "Spatz (Passer domesticus)",
  "Stockente (Anas platyrhynchos)",
  "Trauerseeschwalbe (Chlidonias niger)",
  "Unken (Bombina)",
  "Waldameisen (Formica)",
  "Waldeidechse (Zootoca)",
  "Waldiltis (Mustela putorius)",
  "Waldkauz (Strix aluco)",
  "Waldrapp (Geronticus eremita)",
  "Waldschnepfe (Scolopax rusticola)",
  "Wanderfalke (Falco peregrinus)",
  "Waschbär (Procyon)",
  "Wespen (Vespinae)",
  "Wiesenweihe (Circus pygargus)",
  "Wildbienen (Apidae)",
  "Wildkaninchen (Oryctolagus cuniculus)",
  "Wildkatze (Felis silvestris silvestris)",
  "Wildschwein (Sus scrofa)",
  "Wolf (Canis lupes lupes)",
}

export default AnimalKind;